### ISSUE TITLE
Todo List:

### ISSUE THREAD

**Issue by fundies** [fundies/Crash2D#4]
- [ ] Add tests for circle class
- [ ] circle contains circle method
- [ ] Rename line class to segment
- [ ] Fix consistency in segment class functions
- [ ] Add circle intersects polygon method
- [ ] A circle contains polygon method
- [ ] Add scaling to shapes
- [ ] Phase out Recalc Method
- [ ] Ad methods for getting the collision manifold
